### ISSUE TITLE
Custom Web Publishing technology disabled (CWP).

### ISSUE THREAD

**Issue by ibenettaleb** [chris-schmitz/TaskWithL5SimpleFM#1]
Hi,
I'm trying to connect Filemaker database, i tired all the steps given
https://github.com/chris-schmitz/TaskWithL5SimpleFM
but it showing me the below error...

GeneralException in L5SimpleFMBase.php line 102:
Custom Web Publishing technology disabled (CWP). Command used: {"-db":"Task Databases","-lay":"web_tasks","-findall":null}

I'm not getting from where this thing is happening....
Can any one suggest me regarding this issue.... Any Help

**Comment by chris-schmitz** [comment]
Hey,

This line in the exception:

```
Custom Web Publishing technology disabled (CWP)
```

makes me think that either CWP isn't turned on on your FileMaker Server or laravel can't actually see the filemaker server or port. 

Double check to be sure that custom web publishing is turn on. You should only need it on for XML, but you may want to try turning it on for both xml and php just to see if you can get it up and running. 

Let me know how it goes.

**Comment by ibenettaleb** [comment]
custom web publishing is turn On :
![2017-05-11_9-42-02](https://cloud.githubusercontent.com/assets/28574987/25940503/3ea6f4ce-362e-11e7-82d3-b52640c46937.png)

And i turn on both xml and php :
![2017-05-11_9-45-44](https://cloud.githubusercontent.com/assets/28574987/25940644/bcd06812-362e-11e7-92f8-b817f7334e65.png)

And still i have Error

**Comment by ibenettaleb** [comment]
I try to Enter in FileMaker WebDirect and it gave me this message :
![2017-05-11_9-52-09](https://cloud.githubusercontent.com/assets/28574987/25940974/c01d03e4-362f-11e7-9c40-e38dea2644a0.png)
Thank you For helping

**Comment by ibenettaleb** [comment]
I enabled **XML Publishing.**
And It Worked
Thank You :+1:

**Comment by chris-schmitz** [comment]
Awesome :) I'm glad you're good to go!
